---

- name: "update server" 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    - ENVIRONMENT: ""
    - DOCKER_USR: "techdemowz"
    - DOCKER_PWD: "Comipems01"

  pre_tasks:
    - name: "wait 60 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 60

    - name: "Install python for Ansible."
      become: true
      raw: apt -y update && apt install -y python3
      changed_when: false

  roles:
    - update-server