apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels: 
    app: capstone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
        role: rolling-update
    spec:
      containers:
      - name: capstone-container
        image: techdemowz/capstone:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1