version: 2.1

jobs:
  first-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout 
      - run:
          name: first-job
          command: |
            echo "first-job executed"

  python-linting:
    docker:
      - image: python:3.7-slim
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd code
            ls -la
            pip install --upgrade pip
            python3 -m venv .capstone
            source .capstone/bin/activate
            pip install --trusted-host pypi.python.org -r requirements/base.txt
      - run:
          name: run python lint
          command: |
            cd code
            ls -la
            source .capstone/bin/activate
            pylint main.py

  docker-linting:
    docker:
      - image: python:3.7-slim
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get -y update
            apt -y install wget
            cd code
            ls -la
            python3 -m venv .capstone
            source .capstone/bin/activate
            #install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - run:
          name: run docker lint
          command: |
            cd code
            ls -la
            source .capstone/bin/activate
            hadolint Dockerfile

workflows:
  default:
    jobs:
      - first-job
      - python-linting
      - docker-linting