version: 2.1

jobs:
  first-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout 
      - run:
          name: first-job
          command: |
            echo "first-job executed"

  python-linting:
    docker:
      - image: python:3.7-slim
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            ls -la
            pip install --upgrade pip
            python3 -m venv .capstone
            source .capstone/bin/activate
            pip install --trusted-host pypi.python.org -r requirements/base.txt
      - run:
          name: run python lint
          command: |
            . .capstone/bin/activate
            pylint --disable=R,C,W1203,W1202 app.py

workflows:
  default:
    jobs:
      - first-job
      - python-linting