version: 2.1

commands:
  destroy-environment:
    description: Destroy cloudformation stack
    parameters:
      workflow-id:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name capstone-<<parameters.workflow-id>>


jobs:
  python-linting:
    working_directory: ~/repo
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd code
            ls -la
            pip install --upgrade pip
            python3 -m venv .capstone
            source .capstone/bin/activate
            pip install --trusted-host pypi.python.org -r requirements/base.txt
      - run:
          name: run python lint
          command: |
            cd code
            ls -la
            source .capstone/bin/activate
            pylint main.py

  docker-linting:
    working_directory: ~/repo
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get -y update
            apt -y install wget
            cd code
            ls -la
            python3 -m venv .capstone
            source .capstone/bin/activate
            #install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - run:
          name: run docker lint
          command: |
            cd code
            ls -la
            source .capstone/bin/activate
            hadolint Dockerfile

  run-tests:
    working_directory: ~/repo
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd code
            ls -la
            python3 -m venv .capstone
            source .capstone/bin/activate
            pip install -r requirements/base.txt
      - run:
          name: run pytest
          command: |
            cd code
            ls -la
            source .capstone/bin/activate
            pytest

  build-docker-img:
    working_directory: ~/repo
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - code/caches/capstone.tar
      - run:
          name: Load Docker image layer cache
          command: |
            cd code
            set +o pipefail
            docker load -i /caches/capstone.tar | true
      - run:
          name: Build application Docker image
          command: |
            cd code
            docker build --tag=techdemowz/capstone:latest --cache-from=capstone -t capstone .
      - run:
          name: Save Docker image layer cache
          command: |
            cd code
            mkdir -p /caches
            docker save -o /caches/capstone.tar capstone
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - code/caches/capstone/.tar
      - run:
          name: Upload docker image
          command: |
            cd code
            docker login -u=techdemowz -p=Comipems01
            docker push techdemowz/capstone:latest

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar
          command: yum install -y tar gzip   
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            ls -la
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=capstone \
              --stack-name "capstone-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"   
      - run:
          name: Add EC2 ip to ansible inventory
          command: |
            ls -la
            yum -y install tar gzip
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Name,Values=capstone-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
            --output text >> ~/project/.circleci/ansible/inventory.txt
            cat ~/project/.circleci/ansible/inventory.txt
            echo ${CIRCLE_WORKFLOW_ID:0:7}
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      - destroy-environment:
          workflow-id: "${CIRCLE_WORKFLOW_ID}"

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
           fingerprints: ["78:eb:55:9e:f4:f5:c6:d9:dc:f2:b0:5b:a5:9b:8c:0d"]
      - attach_workspace:    
         at: ~/   
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm curl
            pip install awscli 
      - run:
          name: Configure server with ansible
          command: |
            cd .circleci/ansible
            cat inventory.txt
            ansible-playbook -i inventory.txt configure-server.yml
      - destroy-environment:
          workflow-id: "${CIRCLE_WORKFLOW_ID}"

  smoke-test:
    docker:
      - image: python:3.7-slim
    steps:
      - checkout 
      - run:
          name: Install dependencies
          command: |
            apt-get -y -qq update
            apt-get -y -qq install tar gzip curl
            apt-get -qq install awscli
      - run:
          name: Make test request 
          command: |
            export EC2_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --filters "Name=tag:Name,Values=capstone-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output=text)
            export BACKEND_URL="http://${EC2_IP}:8000"
            echo "${BACKEND_URL}"
            sleep 60
            if curl "${BACKEND_URL}" | grep "Hello"
            then
                return 0
            else
                return 1
            fi
      - destroy-environment:
          workflow-id: "${CIRCLE_WORKFLOW_ID}"

  promote-deployment:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum -y install tar gzip 
      - attach_workspace:
          at: ~/
      - run:
          name: Destroy old deployments 
          command: |
            for stack in $(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --stack-status-filter CREATE_COMPLETE --no-paginate --output text)
            do
              echo "$stack"
              if [[ $stack == *"capstone-${CIRCLE_WORKFLOW_ID:0:7}"* ]]
                then
                  echo "$stack is the same"
              else 
                  echo "$stack is not the same"
                  aws cloudformation delete-stack --stack-name "$stack"
                fi
            done
      - destroy-environment:
          workflow-id: "${CIRCLE_WORKFLOW_ID}"

workflows:
  default:
    jobs:
      - python-linting
      - docker-linting
      - run-tests:
          requires: [python-linting, docker-linting]
      - build-docker-img:
          requires: [run-tests]
      - deploy-infrastructure:
          requires: [build-docker-img]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - smoke-test:
          requires: [configure-infrastructure]
      - promote-deployment:
          requires: [smoke-test]