  - name: "update kubernetes with latest image"
    shell: |
      kubectl rollout restart deployment/capstone    
  - name: "wait 60 seconds for target connection to become reachable/usable."
    wait_for_connection: 
        delay: 60